### ISSUE TITLE
关于跳转找不到about

### ISSUE THREAD

**Issue by ranchenglin** [zheli-design/hexo-theme-one-paper#1]
关于里面想放一个介绍，我应该放在哪。
可以加个标签或分类么，根据不同的类型查看文章。谢谢谢谢，小白的想法。

**Comment by zheli-design** [comment]
你好。

要加单页的话请这么操作：
1. 首先在 source 中新建一个文件夹，例：hello
2. 在 hello 中创建一个 index.md 文件，在 md 中编辑你想展示的内容
3. 编辑 themes/one-paper/_config.yml：
```
menu:
  首页: /
  归档: /archives
  关于: /about
  你好: /hello
```

---

标签页、文字分类页等后续有空我会加上的，敬请期待。

**Comment by ranchenglin** [comment]
> 你好。
> 
> 要加单页的话请这么操作：
> 
> 1. 首先在 source 中新建一个文件夹，例：hello
> 2. 在 hello 中创建一个 index.md 文件，在 md 中编辑你想展示的内容
> 3. 编辑 themes/one-paper/_config.yml：
> 
> ```
> menu:
>   首页: /
>   归档: /archives
>   关于: /about
>   你好: /hello
> ```
> 
> 标签页、文字分类页等后续有空我会加上的，敬请期待。

了解了，感谢，期待更多人看到！！！

**Comment by ranchenglin** [comment]
> 你好。
> 
> 要加单页的话请这么操作：
> 
> 1. 首先在 source 中新建一个文件夹，例：hello
> 2. 在 hello 中创建一个 index.md 文件，在 md 中编辑你想展示的内容
> 3. 编辑 themes/one-paper/_config.yml：
> 
> ```
> menu:
>   首页: /
>   归档: /archives
>   关于: /about
>   你好: /hello
> ```
> 
> 标签页、文字分类页等后续有空我会加上的，敬请期待。

我又发现一个问题，就是文章页面，上面的title是返回首页，箭头也是返回首页，有办法让箭头返回上一页么。

**Comment by zheli-design** [comment]
> 

试一下 `<a onclick="javascript:history.back(-1);">返回</a>`？

之前返回按钮确实是「返回上一级」的，但是如果复制单文页 URL 去打开，点击返回按钮会无效，所以都改成回首页。

**Comment by ranchenglin** [comment]
> > 
> 
> 试一下 `<a onclick="javascript:history.back(-1);">返回</a>`？
> 
> 之前返回按钮确实是「返回上一级」的，但是如果复制单文页 URL 去打开，点击返回按钮会无效，所以都改成回首页。

ok，谢谢！
