### ISSUE TITLE
scss使用问题

### ISSUE THREAD

**Issue by yangbe** [zheli-design/hexo-theme-one-paper#8]
我想把css都换成scss，请问要怎么处理？

<img width="145" alt="image" src="https://user-images.githubusercontent.com/9880101/172006653-d8c599fa-17b3-43fb-a4ae-117f71790765.png">

**Comment by liruiying728** [comment]
你好，可以尝试使用 [第三方转换服务](https://verytoolz.com/css-scss.html) 转换。
